/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tb_main_hotel.UI;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.sql.Date;
import javax.swing.JOptionPane;
import tb_main_hotel.Kamar;
import tb_main_hotel.ListKamar;
import tb_main_hotel.ListReservasi;



/**
 *
 * @author Andaresta
 */
public class DialogaddReservasi extends javax.swing.JDialog {

    private ListReservasi listReservasi;
    private ListKamar listKamar;

    /**
     * Creates new form DialogaddReservasi
     */
    public DialogaddReservasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        DatePickerSettings s = new DatePickerSettings();
        s.setAllowEmptyDates(false);
        s.setVisibleClearButton(false);
        this.datePickerReservasi.setSettings(s);
        this.datePickerReservasi.setDateToToday();
    }
    
    public void setListReservasi(ListReservasi listReservasi) {
        
        this.listReservasi = listReservasi;
    }
    
    public void setListKamar(ListKamar listKamar) {
        
        this.listKamar = listKamar;
        this.listKamar.tampil(this.comboKamar);
    }
    
    public void setTitle(String nama) {
    
        this.titleReservasi.setText("Reservasi Hotel " + nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleReservasi = new javax.swing.JLabel();
        titleIdReservasi = new javax.swing.JLabel();
        titleTanggal = new javax.swing.JLabel();
        titleJumOrang = new javax.swing.JLabel();
        datePickerReservasi = new com.github.lgooddatepicker.components.DatePicker();
        comboJumOrang = new javax.swing.JComboBox<>();
        comboKamar = new javax.swing.JComboBox<>();
        btdoReservasi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);

        titleReservasi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleReservasi.setText("Reservasi");

        titleIdReservasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleIdReservasi.setText("No Kamar");

        titleTanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleTanggal.setText("Tanggal");

        titleJumOrang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleJumOrang.setText("Jumlah Orang");

        comboJumOrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        comboKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btdoReservasi.setText("Submit");
        btdoReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdoReservasiActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleIdReservasi)
                    .addComponent(titleTanggal)
                    .addComponent(titleJumOrang))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleReservasi)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btdoReservasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datePickerReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboJumOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleReservasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleIdReservasi)
                    .addComponent(comboKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleTanggal)
                    .addComponent(datePickerReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleJumOrang)
                    .addComponent(comboJumOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdoReservasi)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btdoReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdoReservasiActionPerformed
        // TODO add your handling code here:
        int jumOrang = 1;
        try {
            jumOrang = Integer.parseInt(this.comboJumOrang.getSelectedItem().toString());
        } catch (Exception e) {
            jumOrang = 1;
        }
        int no = 0;
        int max = 9999;
        try {
            no = Integer.parseInt(this.comboKamar.getSelectedItem().toString());
            /* ambil jml kasur di kamar tsb */
            Kamar kamar = this.listKamar.get(this.listKamar.cari(no));
            if (kamar != null) {
                max = kamar.getJmlKasur();
            }
        } catch (Exception e) {
            no = 0;
        }
        
        if (jumOrang <= max) { 

            Date d = Date.valueOf(this.datePickerReservasi.getDate());
            int hasil = this.listReservasi.doReservation(no, d, jumOrang);
            if (hasil == 1) {
                JOptionPane.showMessageDialog(this, "Kamar sudah terisi pada tanggal tersebut.");
            } else if (hasil == 2) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan reservasi.");
            } else {
                this.comboJumOrang.setSelectedIndex(0);
                this.comboKamar.setSelectedIndex(0);
                this.setVisible(false);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Jumlah kasur tidak mencukupi - hanya ada " + max + " kasur.");
        }
    }//GEN-LAST:event_btdoReservasiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.comboJumOrang.setSelectedIndex(0);
        this.comboKamar.setSelectedIndex(0);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdoReservasi;
    private javax.swing.JComboBox<String> comboJumOrang;
    private javax.swing.JComboBox<String> comboKamar;
    private com.github.lgooddatepicker.components.DatePicker datePickerReservasi;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleIdReservasi;
    private javax.swing.JLabel titleJumOrang;
    private javax.swing.JLabel titleReservasi;
    private javax.swing.JLabel titleTanggal;
    // End of variables declaration//GEN-END:variables
}
